<p></p>
<p><span style="font-weight: 400;">Testing About Us &ldquo;Fastest way to Chat, Meet and Mingle with Local Pet Lovers&rsquo;</span></p>
<p><span style="font-weight: 400;">Canoodle is an excellent all-in-one Platform designed specifically for those we Love the most&hellip;.Our PETS! Whether you want to chat with Local Pet Owners, make new friends or even set up Play Dates at your Local Doggy Parks &ndash; the right one is waiting for you on Canoodle! With millions of Pet owners all over the world, there is an increase in desire to Breed, find a Pet-Sitter due to last minute emergencies / family vacations or just simply connecting with similar pet owners without the need of searching on antiquated websites or joining unnecessary and unreliable social media groups that do not cater to your immediate needs. Canoodle is a one-stop-shop that provides many features that sets us apart from the rest:</span></p>
<ol>
<li><span style="font-weight: 400;"></span><span poppins="" sans-serif="" color:="" 707b8e="" font-size:="" 16px="" line-height:="" 30px="" margin-bottom:="" 15px="" font-weight:="" normal="" style="font-family: helvetica, arial, sans-serif; font-size: 12pt; color: #707b8e;">View and chat with verified Pet Owners in your local areas in a safe and friendly environment right from the app.</span></li>
<li><span poppins="" sans-serif="" color:="" 707b8e="" font-size:="" 16px="" line-height:="" 30px="" margin-bottom:="" 15px="" font-weight:="" normal="" style="font-family: helvetica, arial, sans-serif; font-size: 12pt; color: #707b8e;"></span></li>
<li><span style="font-family: helvetica, arial, sans-serif; font-size: 12pt; color: #707b8e;"><span style="font-weight: 400;"></span><span style="font-weight: 400;">Have the Piece of Mind knowing that your loved one is in great care by receiving unlimited photos and texts of possible matches because our Pets deserve nothing but the Best.</span></span></li>
<li><span style="font-family: helvetica, arial, sans-serif; font-size: 12pt; color: #707b8e;"><span style="font-weight: 400;"></span></span></li>
<li><span style="font-family: helvetica, arial, sans-serif; font-size: 12pt; color: #707b8e;"><span style="font-weight: 400;"></span><span style="font-weight: 400;">Receive notifications of Pet Profile Buddy Hits or matches and view ratings of local Breeders and Dog Parks in your local area.</span></span></li>
<li><span style="font-family: helvetica, arial, sans-serif; font-size: 12pt; color: #707b8e;"><span style="font-weight: 400;"></span></span></li>
<li><span style="font-family: helvetica, arial, sans-serif; font-size: 12pt; color: #707b8e;"><span style="font-weight: 400;"></span><span style="font-weight: 400;">Create exclusive Pet Profiles by adding pictures and tailored information to your pet such as: age, breed and many more!</span></span></li>
</ol>
<p><span style="font-weight: 400;">Did you know Canoodle leads the pack by offering the biggest social networking platforms that bring in people from within your community that may have the same pet as you? Canoodle gives a voice to our Loving furry ones when they need it the most! Canoodle is free to download and use, and that will never change for our main features. However, if you&rsquo;re looking to give your profile a boost, you can always subscribe to Canoodle Plus!</span></p>